export const RoutePaths = {
  main: '/',
  plug: '/plug',
  login: '/login',
  adminLayout: '/admin',
  profile: '/admin/profile',
  orders: '/admin/orders',
  tasks: '/admin/tasks',
  task: '/admin/tasks/:id',
  editTask: '/admin/tasks/:id/edit',
  newTask: '/admin/tasks/new',
  getTaskRoute: (id: string) => `/admin/tasks/${id}`,
  getEditTaskRoute: (id: string) => `/admin/tasks/${id}/edit`,
  clients: '/admin/clients',
  client: '/admin/clients/:id',
  clientNew: '/admin/clients/new',
  staff: '/admin/staff',
  newStaff: '/admin/staff/new',
  oneStaff: '/admin/staff/:id',
  editStaff: '/admin/staff/:id/edit',
  getOneStaffRoute: (id: string) => `/admin/staff/${id}`,
  getEditStaffRoute: (id: string) => `/admin/staff/${id}/edit`,
  deadlines: '/admin/deadlines',
};
